-- MySQL Script generated by MySQL Workbench
-- Saturday, September 02, 2017 PM12:44:41 HKT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema revisioner
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema revisioner
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `revisioner` DEFAULT CHARACTER SET utf8 ;
USE `revisioner` ;

-- -----------------------------------------------------
-- Table `revisioner`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `revisioner`.`users` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `userFirebaseAuthId` VARCHAR(255) NOT NULL,
  `userName` VARCHAR(255) NOT NULL,
  `userPhotoUrl` TEXT NULL,
  `userLastInteractionTimestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `userCreateTimestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `userIntro` TEXT NULL,
  PRIMARY KEY (`userId`),
  INDEX `userFirebaseAuthId_53` (`userFirebaseAuthId` ASC),
  INDEX `userName_54` (`userName` ASC),
  FULLTEXT INDEX `userName_55` (`userName` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `revisioner`.`questionSets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `revisioner`.`questionSets` (
  `questionSetId` INT(11) NOT NULL AUTO_INCREMENT,
  `userId` INT(11) NOT NULL,
  `questionSetTitle` TEXT NOT NULL,
  `questionSetIntro` TEXT NULL,
  `questionSetSubject` VARCHAR(255) NULL,
  `questionSetCreateTimestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `questionSetLastUpdateTimestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`questionSetId`),
  INDEX `userId_35` (`userId` ASC),
  FULLTEXT INDEX `questionSetTitle_36` (`questionSetTitle` ASC),
  FULLTEXT INDEX `questionSetIntro_37` (`questionSetIntro` ASC),
  INDEX `questionSetSubject_38` (`questionSetSubject` ASC),
  FULLTEXT INDEX `questionSetSubject_39` (`questionSetSubject` ASC),
  CONSTRAINT `userId_40`
    FOREIGN KEY (`userId`)
    REFERENCES `revisioner`.`users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `revisioner`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `revisioner`.`questions` (
  `questionId` INT NOT NULL AUTO_INCREMENT,
  `questionSetId` INT NOT NULL,
  `questionTitle` MEDIUMTEXT NULL DEFAULT NULL,
  `questionContent` MEDIUMTEXT NOT NULL,
  `questionMediaUrl` MEDIUMTEXT NULL DEFAULT NULL,
  `questionType` VARCHAR(255) NOT NULL,
  `questionCreateTimestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `questionLastUpdateTimestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`questionId`),
  INDEX `questionSetId_15` (`questionSetId` ASC),
  FULLTEXT INDEX `questionTitle_16` (`questionTitle` ASC),
  FULLTEXT INDEX `questionContent_17` (`questionContent` ASC),
  INDEX `questionType_18` (`questionType` ASC),
  CONSTRAINT `questionSetId_22`
    FOREIGN KEY (`questionSetId`)
    REFERENCES `revisioner`.`questionSets` (`questionSetId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `revisioner`.`questionAnswers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `revisioner`.`questionAnswers` (
  `questionAnswerId` INT NOT NULL AUTO_INCREMENT,
  `questionId` INT(11) NOT NULL,
  `questionAnswerMediaUrl` TEXT NULL,
  `questionAnswerText` TEXT NOT NULL,
  `questionAnswerIsCorrect` TINYINT(1) NOT NULL,
  `questionAnswerScore` INT(11) NOT NULL,
  `questionAnswerCreateTimestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `questionAnswerLastUpdateTimestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`questionAnswerId`),
  INDEX `questionId` (`questionId` ASC),
  CONSTRAINT `questionId`
    FOREIGN KEY (`questionId`)
    REFERENCES `revisioner`.`questions` (`questionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `revisioner`.`userTags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `revisioner`.`userTags` (
  `userTagId` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `userTagContent` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`userTagId`),
  INDEX `userId_56` (`userId` ASC),
  INDEX `userTagContent_57` (`userTagContent` ASC),
  FULLTEXT INDEX `userTagContent_58` (`userTagContent` ASC),
  CONSTRAINT `userId_59`
    FOREIGN KEY (`userId`)
    REFERENCES `revisioner`.`users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `revisioner`.`questionTags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `revisioner`.`questionTags` (
  `questionTagId` INT NOT NULL AUTO_INCREMENT,
  `questionTagContent` VARCHAR(255) NOT NULL,
  `questionId` INT(11) NOT NULL,
  PRIMARY KEY (`questionTagId`),
  INDEX `questionId_49` (`questionId` ASC),
  INDEX `questionTagContent_50` (`questionTagContent` ASC),
  FULLTEXT INDEX `questionTagContent_51` (`questionTagContent` ASC),
  CONSTRAINT `questionId_52`
    FOREIGN KEY (`questionId`)
    REFERENCES `revisioner`.`questions` (`questionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `revisioner`.`questionSetsTags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `revisioner`.`questionSetsTags` (
  `questionSetTagId` INT NOT NULL AUTO_INCREMENT,
  `questionSetId` INT NOT NULL,
  `questionSetTagContent` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`questionSetTagId`),
  INDEX `questionSetId_41` (`questionSetId` ASC),
  INDEX `questionSetContent_42` (`questionSetTagContent` ASC),
  FULLTEXT INDEX `questionSetContent_43` (`questionSetTagContent` ASC),
  CONSTRAINT `questionSetId_44`
    FOREIGN KEY (`questionSetId`)
    REFERENCES `revisioner`.`questionSets` (`questionSetId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `revisioner`.`questionSetFollows`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `revisioner`.`questionSetFollows` (
  `questionSetFollowId` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `questionSetId` INT NOT NULL,
  `questionSetFollowTimestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`questionSetFollowId`),
  INDEX `userId_25` (`userId` ASC),
  INDEX `questionSetId_26` (`questionSetId` ASC),
  CONSTRAINT `userId_27`
    FOREIGN KEY (`userId`)
    REFERENCES `revisioner`.`users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `questionSetId_28`
    FOREIGN KEY (`questionSetId`)
    REFERENCES `revisioner`.`questionSets` (`questionSetId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `revisioner`.`questionSumbits`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `revisioner`.`questionSumbits` (
  `questionSumbitId` INT NOT NULL AUTO_INCREMENT,
  `userId` INT NOT NULL,
  `questionAnswerId` INT NOT NULL,
  `questionSumbitTimestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`questionSumbitId`),
  INDEX `userId_45` (`userId` ASC),
  INDEX `questionAnswerId_46` (`questionAnswerId` ASC),
  CONSTRAINT `questionAnswerId_47`
    FOREIGN KEY (`questionAnswerId`)
    REFERENCES `revisioner`.`questionAnswers` (`questionAnswerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `userId_48`
    FOREIGN KEY (`userId`)
    REFERENCES `revisioner`.`users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `revisioner`.`questionReactionTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `revisioner`.`questionReactionTypes` (
  `questionReactionType` VARCHAR(255) NOT NULL,
  `questionReactionTypeWeight` INT NOT NULL,
  UNIQUE INDEX `questionReactionType_UNIQUE` (`questionReactionType` ASC),
  PRIMARY KEY (`questionReactionType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `revisioner`.`questionReactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `revisioner`.`questionReactions` (
  `questionReactionId` INT NOT NULL AUTO_INCREMENT,
  `questionReactionType` VARCHAR(255) NOT NULL,
  `questionId` INT NOT NULL,
  `userId` INT NOT NULL,
  `questionReactionTimestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`questionReactionId`),
  INDEX `questionReactionType_9` (`questionReactionType` ASC),
  INDEX `questionId_10` (`questionId` ASC),
  INDEX `userId_11` (`userId` ASC),
  CONSTRAINT `questionId_12`
    FOREIGN KEY (`questionId`)
    REFERENCES `revisioner`.`questions` (`questionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `userId_13`
    FOREIGN KEY (`userId`)
    REFERENCES `revisioner`.`users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `questionReactionType_14`
    FOREIGN KEY (`questionReactionType`)
    REFERENCES `revisioner`.`questionReactionTypes` (`questionReactionType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `revisioner`.`questionSetReactionTypes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `revisioner`.`questionSetReactionTypes` (
  `questionSetReactionType` VARCHAR(255) NOT NULL,
  `questionSetReactionTypeWeight` INT NOT NULL,
  UNIQUE INDEX `questionReactionType_UNIQUE` (`questionSetReactionType` ASC),
  PRIMARY KEY (`questionSetReactionType`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `revisioner`.`questionSetReactions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `revisioner`.`questionSetReactions` (
  `questionSetReactionId` INT NOT NULL AUTO_INCREMENT,
  `questionSetReactionType` VARCHAR(255) NOT NULL,
  `questionSetId` INT NOT NULL,
  `userId` INT NOT NULL,
  `questionSetReactionTimestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`questionSetReactionId`),
  INDEX `questionSetReactionType_29` (`questionSetReactionType` ASC),
  INDEX `questionSetId_30` (`questionSetId` ASC),
  INDEX `userId_31` (`userId` ASC),
  CONSTRAINT `questionSetId_32`
    FOREIGN KEY (`questionSetId`)
    REFERENCES `revisioner`.`questionSets` (`questionSetId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `questionSetReactionType_33`
    FOREIGN KEY (`questionSetReactionType`)
    REFERENCES `revisioner`.`questionSetReactionTypes` (`questionSetReactionType`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `userId_34`
    FOREIGN KEY (`userId`)
    REFERENCES `revisioner`.`users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `revisioner`.`questionComments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `revisioner`.`questionComments` (
  `questionCommentId` INT NOT NULL AUTO_INCREMENT,
  `questionId` INT NOT NULL,
  `userId` INT NOT NULL,
  `questionCommentContent` TEXT NOT NULL,
  `questionCommentCreateTimestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `questionCommentLastUpdateTimestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`questionCommentId`),
  INDEX `questionId_4` (`questionId` ASC),
  INDEX `userId_5` (`userId` ASC),
  FULLTEXT INDEX `questionCommentContent_6` (`questionCommentContent` ASC),
  CONSTRAINT `questionId_7`
    FOREIGN KEY (`questionId`)
    REFERENCES `revisioner`.`questions` (`questionId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `userId_8`
    FOREIGN KEY (`userId`)
    REFERENCES `revisioner`.`users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `revisioner`.`questionSetComments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `revisioner`.`questionSetComments` (
  `questionSetCommentId` INT NOT NULL AUTO_INCREMENT,
  `questionSetId` INT NOT NULL,
  `userId` INT NOT NULL,
  `questionSetCommentContent` TEXT NOT NULL,
  `questionSetCommentCreateTimestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `questionSetCommentLastUpdateTimestamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`questionSetCommentId`),
  INDEX `questionSetId_19` (`questionSetId` ASC),
  INDEX `userId_20` (`userId` ASC),
  FULLTEXT INDEX `questionSetCommentContent_21` (`questionSetCommentContent` ASC),
  CONSTRAINT `questionSetId_23`
    FOREIGN KEY (`questionSetId`)
    REFERENCES `revisioner`.`questionSets` (`questionSetId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `userId_24`
    FOREIGN KEY (`userId`)
    REFERENCES `revisioner`.`users` (`userId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
